package com.spring.ai.dto;

public enum JobTitle {
    HUMAN_RESOURCES_REPRESENTATIVE,
    PURCHASING_MANAGER,
    ACCOUNTING_MANAGER,
    STOCK_CLERK,
    ACCOUNTANT,
    STOCK_MANAGER,
    SALES_MANAGER,
    SALES_REPRESENTATIVE,
    ADMINISTRATION_VICE_PRESIDENT,
    SHIPPING_CLERK,
    PROGRAMMER,
    FINANCE_MANAGER,
    MARKETING_MANAGER,
    PURCHASING_CLERK,
    MARKETING_REPRESENTATIVE,
    AWAY
}

